server:
  port: 8905
  servlet:
    context-path: /
#upload:
#  filePath:  /opt/data/files/
spring:
  application:
    name: pegasi-app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app_v2?useUnicode=true&characterEncoding=UTF-8
    username: bgservice
    password: PX7dxFxAbSWDbG6N
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    password: 1234
    port: 6379
    host: 127.0.0.1
    timeout: 5000
  activemq:
    password: admin
    user: admin
    broker-url: tcp://localhost:61608
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      host: localhost
      port: 27017
      database: test
pillow:
  upload:
    path: /opt/data/web/healthglass/pillow/

file:
  upload:
    path: /opt/data/files/
swagger:
  enable: true
#  servlet:
#      multipart:
#        max-file-size: 10240000
#        max-request-size: 10240000